### ISSUE TITLE
Cartoonifying an Image using OpenCV

### ISSUE THREAD

**Issue by undetectablevirus** [geekquad/Image-Processing-OpenCV#107]
We will use OpenCV to get the cartoonised version of an image by applying filters.

**Comment by sal-glitch** [comment]
Hey I would like to work on this issue too. I am familiar with openCV and am a GSSoC participant

**Comment by anandhu-eng** [comment]
Hello, I am a gssoc participant and a python enthusiast. Would be very happy to work on this project. Please do assign it to me:)

**Comment by undetectablevirus** [comment]
@geekquad Kindly assign this to me.

**Comment by dsrao711** [comment]
@geekquad  , I would really like to work on this issue . Also , I can update the readme file with a proper description of the code 
Please assign this to me as a GSSOC Participant

**Comment by geekquad** [comment]
Assigning you with the same @undetectablevirus . Please be more focused on the implementation of the processing technique and not the application.

**Comment by NikkiPriya** [comment]
Please assign it to me I want to work on it.

**Comment by ainy-123** [comment]
> Assigning you with the same @undetectablevirus . Please be more focused on the implementation of the processing technique and not the application.

Hey @geekquad ,can I work on this issue? It seems assignee is inactive for a long time.
If anyone is not working on this issue, kindly assign this to me.

**Comment by geekquad** [comment]
> > Assigning you with the same @undetectablevirus . Please be more focused on the implementation of the processing technique and not the application.
> 
> Hey @geekquad ,can I work on this issue? It seems assignee is inactive for a long time.
> If anyone is not working on this issue, kindly assign this to me. I will raise the PR on the same day of issue assignment.

Hey @ainy-123, not needed right now as we are not accepting any projects for now.
