### ISSUE TITLE
Text Recognition With Real Time Image Capturing

### ISSUE THREAD

**Issue by undetectablevirus** [geekquad/Image-Processing-OpenCV#108]
We will capture the image in real time using Webcam and recognize the text from that image using OCR.

**Comment by geekquad** [comment]
Hey @undetectablevirus, how exactly are you planning to do so?

**Comment by raj-gupta1** [comment]
Give this issue to me. I will use OpenCV and tesseract library using OpenCV East DL model.

**Comment by undetectablevirus** [comment]
@geekquad I will capture the image in real time using WebCam and then will be using OCR and tesseract library to read the text.

**Comment by undetectablevirus** [comment]
@geekquad What's the update on this issue?

**Comment by undetectablevirus** [comment]
@geekquad What about this issue?

**Comment by geekquad** [comment]
Hey @undetectablevirus, 
we are focusing more on the implementation side of Image Processing techniques using **OpenCV** and not on its application.
Feel free to add Techniques here.
