### ISSUE TITLE
Gender Detection

### ISSUE THREAD

**Issue by aakriti1318** [geekquad/Image-Processing-OpenCV#118]
Hey, GSSOC'21 Participant.
I would like to build a script for gender detection. Please assign  me this.

**Comment by raj-gupta1** [comment]
Please, assign this issue to me. I will use CNN with OpenCV, NumPy, and pafy library. Accuracy will be high.

**Comment by geekquad** [comment]
We are accepting various techniques used in Image Processing and not its application. Feel free to create an issue again if I misunderstood something. Thankyou.
