### ISSUE TITLE
Bitwise operations on Images

### ISSUE THREAD

**Issue by Divyang0601** [geekquad/Image-Processing-OpenCV#132]
The notebook will demonstrate how we can apply bitwise operations like AND, OR, and NOT upon images, to alter the current BGR scheme of the image

**Comment by geekquad** [comment]
Provide a description for the same.

**Comment by Divyang0601** [comment]
> Provide a description for the same.

Just did

**Comment by geekquad** [comment]
Assigning you with the same @Divyang0601.

**Comment by geekquad** [comment]
Hey @Sukriti-sood, a PR is already made for the same.
Please look out for another issues. We need help with plenty of them.

**Comment by Divyang0601** [comment]
> Hey @Sukriti-sood, a PR is already made for the same.
> Please look out for another issues. We need help with plenty of them.

Pls review my pull request for this issue PR #169

**Comment by ainy-123** [comment]
hey @geekquad ,Can I work on this issue under GSSoC'21?

**Comment by geekquad** [comment]
@ainy-123 already implemented,
