### ISSUE TITLE
Optical Flow

### ISSUE THREAD

**Issue by abh33** [geekquad/Image-Processing-OpenCV#140]
Hi. I would like to work on Optical Flow. I am a Gssoc '21 participant

**Comment by geekquad** [comment]
Hey @abh33, what exactly are you planning to do here?

**Comment by ras-29** [comment]
Hello @geekquad. I would like to work on Optical flow, implementing Lucas-Kanade and Gunner Farneback's algorithm. I request you to assign this topic to me.
Thank you.
