### ISSUE TITLE
Face Tracking using Meanshift and Camshift algorithm

### ISSUE THREAD

**Issue by iamakkkhil** [geekquad/Image-Processing-OpenCV#150]
Meanshift and Camshift algorithm can be very well implemented to track detected faces in a live video, we can also do a comparative study which algorithm is better. 
I am a GSSoC participant and would like to work on this issue, kindly assign me the same @geekquad @kritikaparmar-programmer .

**Comment by geekquad** [comment]
Hey @iamakkkhil, go ahead!
Focus more on the implementation of the algorithm rather than its application.

**Comment by noviicee** [comment]
Is it still open..?
Can I take this up @geekquad ?
