### ISSUE TITLE
Drawing on live camera

### ISSUE THREAD

**Issue by iamakkkhil** [geekquad/Image-Processing-OpenCV#151]
This script demonstrates drawing of various shapes on a live camera feed from a webcam using various mouse events in OpenCV.
I would like to work on this issue would you please assign me the same @geekquad @kritikaparmar-programmer

**Comment by geekquad** [comment]
Hey @iamakkkhil, which Image Processing technique will be used here?

**Comment by iamakkkhil** [comment]
Drawing on live camera feed the desired shapes through <b>Mouse call back functions</b>.

**Comment by geekquad** [comment]
Hey @iamakkkhil, I don't think that is an Image Processing technique. 
Feel free to raise another issue If I missed out on something,
