### ISSUE TITLE
Real time document Scanner 

### ISSUE THREAD

**Issue by Saptar001** [geekquad/Image-Processing-OpenCV#165]
Hello,
I want to work on this issue "Real time document scanner" where the user could scan a document through his/her camera and could save the scanned image in the device.

I would be very glad if I am assigned with this issue to work on for GSSOC,21
(I hope and guess that this issue or similar to this hasn't been assigned to anyone till now)

Thank You ! :)

**Comment by geekquad** [comment]
Hey @Saptar001, we are focusing more on the implementation side of various Image Processing techniques and not on its application using various projects. 
Feel free to reopen this issue if I have misunderstood something.
Lookout for issues, we have plenty of them left and more on their way. 
Thankyou.
