### ISSUE TITLE
Broken links in the Readme file.

### ISSUE THREAD

**Issue by noviicee** [geekquad/Image-Processing-OpenCV#170]
The provided links in the *Contribution Guidelines* part of the README are not working. 
I can fix them!

**Comment by geekquad** [comment]
Hey @noviicee, please attach a screenshot marking the link that is broken. Thankyou.

**Comment by noviicee** [comment]
@geekquad 
Sure!

In the *Contribution Guidelines* of the README file,

When you click here-
![Screenshot (1681)](https://user-images.githubusercontent.com/72334601/114318640-8d36a600-9b2b-11eb-9edb-5608360618ce.png)

You are redirected to here-
![Screenshot (1686)](https://user-images.githubusercontent.com/72334601/114318659-a8a1b100-9b2b-11eb-8690-2fce1bf7c3eb.png)

And when you click here-
![Screenshot (1684)](https://user-images.githubusercontent.com/72334601/114318694-df77c700-9b2b-11eb-875b-0a9540cb7397.png)

You are redirected to here-
![Screenshot (1687)](https://user-images.githubusercontent.com/72334601/114318716-edc5e300-9b2b-11eb-8728-396066b012d2.png)

**Comment by geekquad** [comment]
Hey @noviicee, go ahead!
