### ISSUE TITLE
Colpr detection using HSV colorspace

### ISSUE THREAD

**Issue by varshakr1298** [geekquad/Image-Processing-OpenCV#177]
Hello, I am GSSoC'21 participant, this code will detect all the blue color present in the surrounding or area Captured by primary camera of a device.

Kindly assign me this issue

**Comment by geekquad** [comment]
Hey @varshakr1298, will this include any specific Image Processing technique we currently don't have?

**Comment by varshakr1298** [comment]
In this I am basically creating a mask and then using bitwise and operation

**Comment by geekquad** [comment]
Hey @varshakr1298, I guess these already exist. 
Feel free to check out any other issue you can contribute to. 
Thank you.

**Comment by varshakr1298** [comment]
Okay thank you!
