### ISSUE TITLE
Live Sketcher using OpenCV Library

### ISSUE THREAD

**Issue by varshakr1298** [geekquad/Image-Processing-OpenCV#178]
I am GSSoC'21 participant I would like to work on this issue. This will create a live sketch of the person being captured through the primary camera of the device using the OpenCV library cv2 and it involves the techniques like Guassian Blurring, Canny edge detection and thresholding.

**Comment by varshakr1298** [comment]
*person or any other object

**Comment by geekquad** [comment]
Already exists.
