### ISSUE TITLE
Neural Style Transfer

### ISSUE THREAD

**Issue by Ayush12062000** [geekquad/Image-Processing-OpenCV#179]
Hello, I want to add and work on Neural style transfer and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in the Python Language, will be using the pre-trained model VGG19.

(Neural style transfer is a technique that takes two images, a Content image and a style reference image, and blends them together so the output image looks like the content image)

Kindly assign this issue to me!
@geekquad @kritikaparmar-programmer

**Comment by geekquad** [comment]
Hey @Ayush12062000, no pre-trained models are allowed. Thankyou.
