### ISSUE TITLE
Using Neural Network for detecting Emotion in video as well as images

### ISSUE THREAD

**Issue by ParthSingh0506** [geekquad/Image-Processing-OpenCV#180]

**Comment by ParthSingh0506** [comment]
@geekquad kindly assign me this issue I am a gssoc21 participant

**Comment by geekquad** [comment]
Hey @ParthSingh0506, will you be using any pre-trained model?

**Comment by ParthSingh0506** [comment]
@geekquad No I will not be using any pre trained model. I will going to use the CNN. Basically I will going to create a new model for this.

**Comment by geekquad** [comment]
Hey @ParthSingh0506, this issue does not match with the sentiment of this repo. 
Please check out any other issues you can contribute to. 
Thankyou.
