### ISSUE TITLE
Face Detection using Haar Cascades

### ISSUE THREAD

**Issue by Saptar001** [geekquad/Image-Processing-OpenCV#183]
Hello @geekquad , I want to work on this issue "Face Detection"  where I would be using  "Haar Cascades".
It would be very nice if I am assigned with this issue as I see no one still worked on this issue (using Haar Cascades ) and I would be glad to work on it. 

Thank You ! :)

**Comment by geekquad** [comment]
Hey @Saptar001, we already have a lot of face detection techniques. 
Can you implement Haar Cascades for something other than face detection?

**Comment by Saptar001** [comment]
@geekquad  what about pedestrain detection( full body detection) using haar cascades from a video ??

**Comment by Saptar001** [comment]
@geekquad  do let me know the above suggestion so that I could start working on it !

:)

**Comment by geekquad** [comment]
Hey @Saptar001, go ahead.
You are doing amazing work. Keep it up 🔥
