### ISSUE TITLE
Add Implementation Of face detection

### ISSUE THREAD

**Issue by NEERAJAP2001** [geekquad/Image-Processing-OpenCV#190]
I'd like to add an implementation of face detection using open cv into [this]( https://github.com/geekquad/Image-Processing-OpenCV/tree/master/Face_Detection) folder.

I'd like to work on this as a part of GSSOC-21

**Comment by geekquad** [comment]
Hey @NEERAJAP2001, this already exists.
Please look out for more issues you can contribute to.
Thankyou.
