### ISSUE TITLE
Histogram Matching in images

### ISSUE THREAD

**Issue by SatYu26** [geekquad/Image-Processing-OpenCV#20]
I wish to add Histogram matching program.

GSSoC'21

**Comment by geekquad** [comment]
Assigning you with the same. Please read the Contributing Guidelines.

**Comment by SatYu26** [comment]
yes sure, will make it today itself.

**Comment by SatYu26** [comment]
@geekquad Please review my pull request.

**Comment by geekquad** [comment]
> @geekquad Please review my pull request.

It will be reviewed. Please be patient. Thankyou.

**Comment by SatYu26** [comment]
> > @geekquad Please review my pull request.
> 
> It will be reviewed. Please be patient. Thankyou.

ok sure.
