### ISSUE TITLE
a facial Lock system

### ISSUE THREAD

**Issue by shantamsultania** [geekquad/Image-Processing-OpenCV#209]
hey, I am thinking of making a facial lock system using OpenCV in which a dataset of current user will be taken and then with the help of which algo will predict if that person is user or not if its the user it will unlock else it will not

**Comment by geekquad** [comment]
Hey @shantamsultania, this doesn't match our sentiment. We are not collecting projects. 
Rather than we are focusing on having various Image Processing techniques. Thankyou.
