### ISSUE TITLE
Fourier Transformation OpenCV

### ISSUE THREAD

**Issue by iamakkkhil** [geekquad/Image-Processing-OpenCV#218]
Fourier Transformation helps to understand the frequency characteristics produced under various filters.
I will also be covering Discrete Fourier transformation algorithm

I am a GSSOC21 participant and I would like to work on the same.

**Comment by iamakkkhil** [comment]
@geekquad can I work on this ??

**Comment by geekquad** [comment]
Sure @iamakkkhil, go ahead.
