### ISSUE TITLE
Simple Image Thresholding

### ISSUE THREAD

**Issue by geekquad** [geekquad/Image-Processing-OpenCV#22]
Implementation of Simple Image Thresholding using nothing but OpenCV.

**Comment by psyduck1203** [comment]
Hey, I'm a GSSoC`21 participant and want to contribute to this repo can you please assign me this issue?

**Comment by geekquad** [comment]
Assigning you with the same.

**Comment by sakshi2707** [comment]
Hey, I'm a GSSoC`21 participant and want to contribute to this repo can you please assign me this issue? @geekquad

**Comment by pallavidhere23** [comment]
Hello ,I am a GSSOC'2021 participant and love to fix this issue. please assign me the issue.

**Comment by ikanani** [comment]
Hello, I am a GSSOC'21 participant and would love to work on this issue. Can you please assign me this?

**Comment by NitiKaur** [comment]
Hello, I am a GSSOC'21 participant and would love to work on this issue. Can you please assign me this?

**Comment by Sibasish-Padhy** [comment]
hello I am a GSSOC participant 2021 participant and love to fix the issue.please assign me the issue.

**Comment by Rajeswari0410** [comment]
Hello! I'm a GSSOC'21 participant and would like to work on this issue.Please assign me this issue.

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by psyduck1203** [comment]
@Rajeswari0410, @einhawking  Sorry but I have already made a PR and it has been merged. @geekquad can you please close this issue.
