### ISSUE TITLE
Image Cartoonification

### ISSUE THREAD

**Issue by dsrao711** [geekquad/Image-Processing-OpenCV#221]
**Is your feature request related to a problem? Please describe.**
Image cartoonification section hasnt been implemented

**Describe the solution you'd like**
<img width="322" alt="cartoon" src="https://user-images.githubusercontent.com/59830064/116817111-7dd2d780-ab82-11eb-9d25-b5b09c096881.png">
Implementing the solution with Open CV

**Comment by dsrao711** [comment]
Please assign me this issue as a GSSOC 21 participant

**Comment by kritikaparmar-programmer** [comment]
Assigning you @dsrao711. Add your code to the Image_cartoonification folder.

**Comment by kritikaparmar-programmer** [comment]
Hey, @dsrao711 Sorry but the pr for the same issue has already been made : 
https://github.com/geekquad/Image-Processing-OpenCV/pull/159
Sorry for the inconvenience, but I'll have to unassign you for the same.
