### ISSUE TITLE
Cartoon effect notebook

### ISSUE THREAD

**Issue by mansi75** [geekquad/Image-Processing-OpenCV#223]
**Is your feature request related to a problem? Please describe.**
Yes. It is for the cartoon effect in OpenCV. 

**Describe the solution you'd like**
I would like to work on the applying cartoon effect on an image, using openCV techniques for image transformation.

**Describe alternatives you've considered**
Using bilateral Filter, adaptive thresholding and other OpenCV techniques to apply cartoon effect. 

**Additional context**

**Comment by mansi75** [comment]
Kindly, assign me this issue.

**Comment by geekquad** [comment]
Hey @mansi75, the issue template is made for you so that you can follow that and describe what the issue/feature is all about. Please use that to let us know what exactly you are up to. Thankyou.

**Comment by mansi75** [comment]
@geekquad Kindly check! Updated.

**Comment by geekquad** [comment]
Hey @mansi75, isn't it something similar to #27 and #107.

**Comment by mansi75** [comment]
@geekquad Yes, it is

**Comment by geekquad** [comment]
Hey @mansi75, it already exists.
