### ISSUE TITLE
Sobel edge detection using OpenCV

### ISSUE THREAD

**Issue by mansi75** [geekquad/Image-Processing-OpenCV#237]
**Is your feature request related to a problem? Please describe.**
Yes, to build a notebook for edge detection using sobel edge detector.

**Describe the solution you'd like**
Sobel edge detector python file along with the complete explanation.

**Describe alternatives you've considered**

**Additional context**

**Comment by geekquad** [comment]
Hey @mansi75, please check [here](https://github.com/geekquad/Image-Processing-OpenCV/blob/master/EdgeDetection/sobel_egde_detection.ipynb). It already exists. 
Thankyou.
