### ISSUE TITLE
Add Github Action Welcome Bot

### ISSUE THREAD

**Issue by Aayush-hub** [geekquad/Image-Processing-OpenCV#24]
Add Github action greeting bot which greets first time contributors with a welcome message and message to follow contributing guidelines.

**Comment by Aayush-hub** [comment]
@geekquad @kritikaparmar-programmer Can I look into this issue?

**Comment by geekquad** [comment]
Sure @Aayush-hub. Go ahead!

**Comment by Aayush-hub** [comment]
@geekquad @kritikaparmar-programmer Waiting for my #23  [PR](https://github.com/geekquad/Image-Processing-OpenCV/pull/23) to be merged. Will make a PR soon after that solving this issue!

**Comment by geekquad** [comment]
Hey @Aayush-hub, you can make a new branch for the same and continue your work.

**Comment by Aayush-hub** [comment]
> Hey @Aayush-hub, you can make a new branch for the same and continue your work.

@geekquad Done :)
