### ISSUE TITLE
I want to add eye detection script using open cv with live video processing

### ISSUE THREAD

**Issue by Ashishsingh619** [geekquad/Image-Processing-OpenCV#241]
I want to add an python script for eye detection using opencv in which i will use live video processing to captures frames and detect eyes of a person .
@geekquad Sir and @unnati914 maam please assign me with this issue.

**Comment by geekquad** [comment]
Hey @Ashishsingh619, we are not accumulating projects.
Just looking for the implementation of various Image Processing techniques and not their application.
If you know some which do not already exist, please feel free to create an issue.
If I missed out on something, feel free to reopen the issue.
