### ISSUE TITLE
Bitwise operations in OpenCV

### ISSUE THREAD

**Issue by RohiniRG** [geekquad/Image-Processing-OpenCV#254]
The implementation and demonstration of various bitwise operations  like AND, OR, NOT, XOR  performed on images using opencv.
 
I am a GSSOC'21 participant and would like to work on this issue.

**Comment by RohiniRG** [comment]
@geekquad @kritikaparmar-programmer please assign me this issue

**Comment by geekquad** [comment]
Sure @RohiniRG, go ahead.
