### ISSUE TITLE
Contrast stretching using Piecewise-Linear Transformation Functions in openCV

### ISSUE THREAD

**Issue by mansi75** [geekquad/Image-Processing-OpenCV#259]
This process expands the range of intensity levels in an image so that it spans the full intensity of the camera or display using OpenCV. Please Kindly assign me this.

**Comment by geekquad** [comment]
Go ahead. Assigning it to you.
Please mention the issue number in the description while making a PR.
Name the folder as ```PiecewiseLinearTransformation```.
