### ISSUE TITLE
Color Detection Readme

### ISSUE THREAD

**Issue by geekquad** [geekquad/Image-Processing-OpenCV#265]
Documentation of the same strictly following this [template](https://github.com/geekquad/Image-Processing-OpenCV/issues/137).

**Comment by Saptar001** [comment]
Hello @geekquad  could you please kindly assign me this issue, as I want to work on this documentation.

Also, mention the folder in which I have to make the changes or add the documentation.

Thank You :)

**Comment by geekquad** [comment]
Hey @Saptar001, go ahead.
Add the documentation in [this](https://github.com/geekquad/Image-Processing-OpenCV/tree/master/ColorDetection) folder.
