### ISSUE TITLE
I Would like to add the following algos (GSSOC 21)

### ISSUE THREAD

**Issue by aswarth123** [geekquad/Image-Processing-OpenCV#27]
- [ ] HarrisCornerDetection
- [ ] Image_Cartoonification
- [ ] FourierTransformation
- [ ] HoughTransformation

Kindly assign this issue to me i would love to contribute as part of GSSOC 21 participant

**Comment by Ashishsingh619** [comment]
Hi, I'm a GSSoC`21 participant and want to contribute to this. I have good knowledge about this topic and want to apply my knowledge to practice, So can you please assign me this issue

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc 21 participant.I already worked on it and I am eager to contribute to this issue .Aiming to contribute a **CLEAN CODE** , **PERFECT README** and **ALL RESOURCES** associated with it.Can you please assign this to me?

**Comment by geekquad** [comment]
Assigning HarrisCornerDetection and ImageCartoonification to @aswarth123.
Assigning FourierTransformation to @Ashishsingh619.
Assigning HoughTransformation to @Rupa-421. 

Please make separate PRs for each issue.
