### ISSUE TITLE
Scale Invariant Feature Transform  using openCV

### ISSUE THREAD

**Issue by mansi75** [geekquad/Image-Processing-OpenCV#291]
Scale Invariant Feature Transform in openCV helps to find keypoints in an image.
Please kindly assign me this.

**Comment by geekquad** [comment]
Hey @mansi75, please take a look at the issues and already existing files before opening an issue.
It already exists. Have a look [here](https://github.com/geekquad/Image-Processing-OpenCV/issues/269).
