### ISSUE TITLE
Watershed Algorithm with custom seeds

### ISSUE THREAD

**Issue by iamakkkhil** [geekquad/Image-Processing-OpenCV#314]
This script will implement the watershed algorithm with custom seeds which will fill automatically fill surrounding areas with the same segmentation class.
 
@geekquad  I would like to work on this issue kindly assign me the same.

**Comment by geekquad** [comment]
Go ahead @iamakkkhil.

**Comment by iamakkkhil** [comment]
@geekquad let me know for any changes
