### ISSUE TITLE
Grid detection

### ISSUE THREAD

**Issue by ras-29** [geekquad/Image-Processing-OpenCV#328]
I would like to work on this topic, implementing cv2.findChessboardCorners() and cv2.findCirclesGrid() functions. I request you to assign this to me.
![Screenshot (591)](https://user-images.githubusercontent.com/78521234/119617984-03fbda00-be20-11eb-99f2-7ddcdcde384e.png)

**Comment by geekquad** [comment]
Hey @ras-29, it has already been implemented. 
Please look out for more. Thankyou.
