### ISSUE TITLE
Want to contribute in the Image Smoothing Repo

### ISSUE THREAD

**Issue by Saptar001** [geekquad/Image-Processing-OpenCV#33]
Hi Saptarshee here, 
I am a participant of GSSOC,21 and want to work and contribute in the Image Smoothing repo.
Could you please assign me the job so that I start working on it ?

**Comment by geekquad** [comment]
Sure @Saptar001. 
Do you want to work on all three?

**Comment by Saptar001** [comment]
@geekquad  
Currently I want to start working on the Gaussian Filtering, if I finish it and if time permits I would also love to proceed for the following two filtering.

**Comment by geekquad** [comment]
Awesome. Assigning Gaussian Filtering to you @Saptar001.
