### ISSUE TITLE
Pepper Effect Filter

### ISSUE THREAD

**Issue by A-kriti** [geekquad/Image-Processing-OpenCV#335]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Pepper Effect Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Pepper Effect Filter". ( OpenCV, Matplotlib, Os, PIL, and NumPy)

**Final Output**
![Screenshot (419)](https://user-images.githubusercontent.com/73133055/119606308-f9394900-be0f-11eb-8bd3-4de64fed044f.png)

**Comment by geekquad** [comment]
Which Image Processing technique will you be using (describe focusing on OpenCV)?

**Comment by A-kriti** [comment]
In this, I am adding noise to the image by using a function that actually takes 2 parameters 1st is the image and the other 1 is probability and in this function i am generating a random number and comparing it with the probability taken and according to that adding noise to it finally making it a pepper effect image.

**Comment by geekquad** [comment]
Hey @A-kriti, not looking for any sort of filters. 
The focus is to have technique implementation and the ones you mentioned are already here.

**Comment by A-kriti** [comment]
okay
