### ISSUE TITLE
Image pixel processing

### ISSUE THREAD

**Issue by swathika1** [geekquad/Image-Processing-OpenCV#339]
**Is your feature request related to a problem? Please describe.**
Encoding and decoding message from image pixels.

**Describe the solution you'd like**
Processing an image to conceal secret messages in images, making use of an ordinary image where a secret message can be hidden among the pixels of the picture. The modified image can be decoded to obtain the original message again.

**Describe alternatives you've considered**
Any random image can be chosen to encode text message.

**Additional context**

The image pixels are obtained from it in hexadecimal form. The r, g, b values are obtained, the original values are manipulated and stored after encoding the message in the picture. The receiver, on the other end, receives the image and can decode the message from the pixels.

Opening this issue as GSSOC' 21 participant.
Please assign this to me if you approve @geekquad.

**Comment by geekquad** [comment]
Hey @swathika1, which Image Processing technique will you be using here?

**Comment by swathika1** [comment]
@geekquad I will be using the PIL (Python Imaging Library) to convert image to RGBA(red-green-blue-alpha), obtain and manipulate its pixels with the text message.
