### ISSUE TITLE
Splash filter

### ISSUE THREAD

**Issue by ras-29** [geekquad/Image-Processing-OpenCV#343]
**Is your feature request related to a problem? Please describe.**
I would like to implement a "splash filter". In this filter, a specific color is detected and masked, the rest of the image is grayscaled.

**Describe the solution you'd like**
To achieve this, concepts used are color detection, masking, and bitwise operations on the images.

**Output**
![Screenshot (594)](https://user-images.githubusercontent.com/78521234/119786221-974f1100-beed-11eb-9ec1-ba3d373d7d2e.png)

**Comment by geekquad** [comment]
Hey @ras-29, is it more of a mini project?

**Comment by ras-29** [comment]
@geekquad yes sir, incorporating 3 basic concepts to get this effect.

**Comment by geekquad** [comment]
Hey @ras-29, the 3 techniques you have mentioned are already been implemented and we are not looking for any projects/mini-proejcts.
