### ISSUE TITLE
Pirates Filter

### ISSUE THREAD

**Issue by A-kriti** [geekquad/Image-Processing-OpenCV#352]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Pirates Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Pirates Filter". ( OpenCV and Matplotlib)

**Final Output context**
![image](https://user-images.githubusercontent.com/73133055/119840999-114dbd00-bf23-11eb-9a7d-2d82fa17ce61.png)

**Comment by geekquad** [comment]
Not accumulating any proejcts.
Focus more on the techniques rather than their applications.
