### ISSUE TITLE
Facial Features detection using OpenCV

### ISSUE THREAD

**Issue by swathika1** [geekquad/Image-Processing-OpenCV#353]
**Is your feature request related to a problem? Please describe.**
Facial features such as eyes, eyebrows, mouth and jaw detection.

@geekquad Please assign this to me if u approve!
Opening this issue as GSSOC' 21 participant.

**Comment by geekquad** [comment]
hey @swathika1, not accepting any kind of projects/mini-projects. 
Please do look out for any techniques you can contribute with.
Thankyou.

**Comment by swathika1** [comment]
@geekquad Its not a mini project its just a technique to obtain the face features.
for example:
input
![image](https://user-images.githubusercontent.com/66555276/120067424-28aeb680-c099-11eb-8237-3378eb4f4f4e.png)

output
![image](https://user-images.githubusercontent.com/66555276/120067428-2ea49780-c099-11eb-9c27-8e4ba2bc1857.png)

**Comment by geekquad** [comment]
So which Image processing techniques will you be using here?

**Comment by swathika1** [comment]
@geekquad  By using openCV along with the dlib, that gives 68 (x, y)-coordinates that map to specific facial structures.

**Comment by geekquad** [comment]
Hey @swathika1, please go through the project description. 
We are focusing on ```Open-CV``` and as such usage of any other Image Processing library is not allowed.
