### ISSUE TITLE
sketch image technique using OpenCV

### ISSUE THREAD

**Issue by swathika1** [geekquad/Image-Processing-OpenCV#364]
**Is your feature request related to a problem? Please describe.**
Convert an image to produce a pencil sketch.

![image](https://user-images.githubusercontent.com/66555276/120069938-1f781680-c0a6-11eb-82bc-69b791fbcca9.png)

![image](https://user-images.githubusercontent.com/66555276/120069942-243cca80-c0a6-11eb-9a57-2c3be0d52f26.png)

(this is not similar to image cartoonification)
@geekquad

**Comment by geekquad** [comment]
We’re not looking for it. Please see if you can contribute to something else. 
Thankyou.
