### ISSUE TITLE
Changing of Color Space

### ISSUE THREAD

**Issue by zenithexpo** [geekquad/Image-Processing-OpenCV#40]
I would like to add implementation of Changing the Color Space of an image (BGR to Gray and HSV).

**Comment by zenithexpo** [comment]
Please assign me this issue under GSSoC'21.

**Comment by Ashishsingh619** [comment]
Hi, I'm a GSSoC`21 participant and want to contribute to this. I have good knowledge about this topic and want to apply my knowledge to practice, So can you please assign me this issue

**Comment by geekquad** [comment]
Hey @zenithexpo. It has already been assigned to someone. 
Please look out for other issues you can contribute to. Will be opening more soon.
Thankyou.
