### ISSUE TITLE
ImageResize

### ISSUE THREAD

**Issue by NitiKaur** [geekquad/Image-Processing-OpenCV#42]
I am a GSSOC participant.Please assign this issue to me

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant.Please assign me this issue.

**Comment by NitiKaur** [comment]
@pallavidhere23 already requested by me. Plz find some other issue! :)

**Comment by geekquad** [comment]
Hey @NitiKaur, this issue has already been assigned to someone earlier. Please lookout for more issues. Will be opening more soon. Thankyou.
