### ISSUE TITLE
Multiple Object Tracking using OpenCV

### ISSUE THREAD

**Issue by ricsin23** [geekquad/Image-Processing-OpenCV#44]
I am a participant of GSSOC'21 and wanted to contribute to this issue. Requesting admins to assign me this issue.

**Comment by riyalamba07** [comment]
Hi, I am a GSsoc'21 participant. I would like to work on this issue. I would request the project maintainers to assign this issue to me.

**Comment by geekquad** [comment]
Assigning you with the same @ricsin23.
