### ISSUE TITLE
Edge-Detection

### ISSUE THREAD

**Issue by Bhumika-Kothwal** [geekquad/Image-Processing-OpenCV#5]
I want to implement Edge Detection Algorithm. Can you please assign it to me?

**Comment by kritikaparmar-programmer** [comment]
Hey, @Bhumika-Kothwal assigning Edge Detection Algorithm to you :)

**Comment by Bhumika-Kothwal** [comment]
> Hey, @Bhumika-Kothwal assigning Edge Detection Algorithm to you :)
> Do tell me if you're a participant of GSSOC'21. I'll add labels accordingly.
> And if participant then only submit PR when GSSOC'21 contributing period starts.

Yes, I am a participant of GSSOC'21.

**Comment by puranjay123** [comment]
hey can you assign me this issue.

**Comment by sakshi2707** [comment]
Hey, I'm a GSSoC`21 participant and want to contribute to this . can you please assign me this issue?

**Comment by Ashishsingh619** [comment]
Hi, I'm a GSSoC`21 participant and want to contribute to this. I have good knowledge about this topic and want to apply my knowledge to practice, So can you  can you please assign me this issue?

**Comment by Ashishsingh619** [comment]
> Hey @Bhumika-Kothwal, @puranjay123, @sakshi2707, and @Ashishsingh619,
> Edge Detection has 4 methods. Do you guys want to split it among yourselves?

I can do canny edge Detection and Robert Edge Detection, I had a doubt should our code be for real time video or a simple image?

**Comment by sakshi2707** [comment]
I can do the Laplacian Operator Edge Detection @geekquad

**Comment by Ashishsingh619** [comment]
@geekquad  I am Ashishsingh619 As you had said I had implemented canny edge Detection and Sobel Edge Detection part please see my pull request for the issue:
https://github.com/geekquad/Image-Processing-OpenCV/issues/5#issuecomment-793553723

**Comment by Bhumika-Kothwal** [comment]
@geekquad I will work on Robert Edge Detection and Prewitt Edge Detection

**Comment by prathimacode-hub** [comment]
Hey, I'm a GSSOC21 participant. I would like to work on this issue. Can you assign it to me?
