### ISSUE TITLE
Hough Transformation

### ISSUE THREAD

**Issue by Ashishsingh619** [geekquad/Image-Processing-OpenCV#56]
I want to implement all the hough transform methods like:
*Hough Line transformation
*Probabilistic Hough Line Transformation
*Hough Circle

To detect the lines and the circles in an Image. 
This are my few implementation on the issue and working upon on it to make it more better:
For Hough circle:
<img width="462" alt="hough_circles" src="https://user-images.githubusercontent.com/62636670/110632225-63f1c580-81cd-11eb-9690-34acd42feecf.PNG">
For Hough Lines:
<img width="146" alt="hough_lines" src="https://user-images.githubusercontent.com/62636670/110632683-ed08fc80-81cd-11eb-8121-0a2910a56151.PNG">

Sir @geekquad and Maam @kritikaparmar-programmer please assign me this issue to work on, I am a GSSoC'21 participant and would love to work on this issue.

**Comment by geekquad** [comment]
Hey @Ashishsingh619, Hough Line transformation is already assigned to someone. 
However, you can move ahead with 
*Probabilistic Hough Line Transformation
*Hough Circle
Happy Coding :)

**Comment by noviicee** [comment]
@geekquad can I take up the Probabilistic Hough Line Transformation part..?

**Comment by geekquad** [comment]
> @geekquad can I take up the Probabilistic Hough Line Transformation part..?

Go ahead @noviicee.

**Comment by noviicee** [comment]
> > @geekquad can I take up the Probabilistic Hough Line Transformation part..?
> 
> Go ahead @noviicee.

Thanks @geekquad 
Created a PR regarding the same..
also, I see that Hough Line transformation is not added, can I take up that part too..?
