### ISSUE TITLE
Harris Corner Detection

### ISSUE THREAD

**Issue by Ashishsingh619** [geekquad/Image-Processing-OpenCV#59]
Hi, I'm a GSSoC`21 participant and want to contribute to this. I have good knowledge about Harris Corner Detection and want to apply my knowledge to practice, So can you please assign me this issue.
@geekquad sir and @kritikaparmar-programmer ma'am.

**Comment by geekquad** [comment]
Hey @Ashishsingh619, this issue has already been assigned to someone. Please check #27.
