### ISSUE TITLE
Writing in Air

### ISSUE THREAD

**Issue by Dhanush2612** [geekquad/Image-Processing-OpenCV#65]
Writing with help of opencv

**Comment by Dhanush2612** [comment]
Kindly assign me this issue.

**Comment by geekquad** [comment]
Hey @Dhanush2612, which Image Processing technique will you be using here?

**Comment by Dhanush2612** [comment]
@geekquad 
Track your hand's movement, using which a user can draw on the screen by moving his finger around.

**Comment by geekquad** [comment]
Hey @Dhanush2612, tracking my hand's movement isn't a technique I suppose. 
Just a reminder that this is repo is focused on having an implementation of various Image Processing techniques and not a collection of projects using OpenCV. 
Please make an issue again if you think I am missing out on something and we will get back to you.
