### ISSUE TITLE
Canny Edge Detection.

### ISSUE THREAD

**Issue by pshivesh8** [geekquad/Image-Processing-OpenCV#66]
Hi, I'm a GSSoC`21 participant and want to contribute to this. I have good knowledge about openCV and want to apply my knowledge to practice, So can you please assign me this issue.

@geekquad , @kritikaparmar-programmer

**Comment by aditisneh** [comment]
Hey, I want to work on this issue , if more people are needed, include me in. :) @geekquad @kritikaparmar-programmer

**Comment by i-akshat-jain** [comment]
Hey, I would like to work and learn more about this, can you please assign this issue to me. (GSSOC21) @geekquad

**Comment by geekquad** [comment]
Hey @pshivesh8, this issue has already been assigned to someone. Please check #5.
