### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [geekquad/Image-Processing-OpenCV#67]
I would like to add contributing.md file . I will contribute by putting steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forked repo as well as local repo as the changes are made to the upstream

I would like to work on this as a part of GSSOC'21

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by khareyash05** [comment]
@Simar05519 I am a participant and I have opened the issue for myself
Sorry!

**Comment by khareyash05** [comment]
@unnati914 Pls add a GSSOc label and a level label to the same

**Comment by khareyash05** [comment]
@unnati914 Thanx
Can i update in existing contributing.md or shall i create a new file namely github-guidelines?

**Comment by khareyash05** [comment]
@unnati914 Attached a PR Have a look!

**Comment by geekquad** [comment]
Hey @khareyash05, isn't it already documented in the project's README?

**Comment by khareyash05** [comment]
@geekquad The README file contains only the steps to create a PR I am adding the following -
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
with proper steps

**Comment by geekquad** [comment]
@khareyash05 will look into it.

**Comment by khareyash05** [comment]
@geekquad is my PR ready to merge?

**Comment by khareyash05** [comment]
@geekquad
