### ISSUE TITLE
Face_Detection Using OpenCV

### ISSUE THREAD

**Issue by Ayush12062000** [geekquad/Image-Processing-OpenCV#68]
Hello, I am Ayush Kesarwani, GSSoC`21 participant, and want to contribute to FACE DETECTION using OpenCV.

Kindly, assign this issue to me.
@geekquad @kritikaparmar-programmer

**Comment by Rupa-421** [comment]
It's duplicate issue found.Already there in [issue](https://github.com/geekquad/Image-Processing-OpenCV/issues/8). Please close it as soon as possible as it may lead to confusion.@geekquad @ImgBotApp@Ayush12062000 @Aanisha @kritikaparmar-programmer @unnati914

**Comment by geekquad** [comment]
Thankyou for bringing it to my notice. 
Hey @Ayush12062000, this has already been assigned to someone.  Please lookout for something else. Thankyou.
