### ISSUE TITLE
Face detection

### ISSUE THREAD

**Issue by lavanya243** [geekquad/Image-Processing-OpenCV#70]
Hey @geekquad  , I am Lavanya Narayanan, a GSSOC, 2021 participant.
I want to work on face detection issue.

I would like to request you to kindly assign me this problem.

**Comment by Rupa-421** [comment]
It's duplicate issue found.Already there in [issue](
https://github.com/geekquad/Image-Processing-OpenCV/issues/8). Please close it as soon as possible as it may lead to confusion.@geekquad @ImgBotApp @lavanya243 @Aanisha @kritikaparmar-programmer @unnati914
