### ISSUE TITLE
Concatenate Images

### ISSUE THREAD

**Issue by soumyavemuri** [geekquad/Image-Processing-OpenCV#77]
Hello, I am a GSSoC '21 participant. I would like to work on adding the [ConcatenateImages](https://github.com/geekquad/Image-Processing-OpenCV/tree/master/ConcatenateImages) directory.

# Description
I would like to develop the code to concatenate Images Horizontally and Vertically using OpenCV, and add a readme.md file to assist in understanding it.

**Comment by geekquad** [comment]
Hey @soumyavemuri, it has been already assiged to someone. Please check #12.
