### ISSUE TITLE
Invisibility Cloak

### ISSUE THREAD

**Issue by Dhanush2612** [geekquad/Image-Processing-OpenCV#87]
Perform Invisibility Cloak designed using python and opencv.

**Comment by Dhanush2612** [comment]
@geekquad kindly assign me this issue.

**Comment by i-akshat-jain** [comment]
@geekquad I have a bit of hands on this part kindly assign me this issue

**Comment by i-akshat-jain** [comment]
@geekquad we have to mask it with RGB only right?

**Comment by aditisneh** [comment]
Hey @unnati914, have you seen that Invisibility Cloak issue #53  was opened 6 days ago, and there are 3 people already in the queue.

**Comment by geekquad** [comment]
Hey @Dhanush2612, @i-akshat-jain @aditisneh, it has already been assigned. Please check it here #53.
If the participant fails to submit the PR in the specified duration, it will be automatically transferred to the next participant. Thankyou.
