### ISSUE TITLE
Face_Detecion 

### ISSUE THREAD

**Issue by anubhav201241** [geekquad/Image-Processing-OpenCV#94]
**Adding Code to the file** 
In Face-Detection folder there is only readme file I want to contribute the code file in it by using python(open-cv)
I want to work upon this submit the code.

Kindly Assigned this part to me :)
I can update the code in more optimized and some features in it

@kritikaparmar-programmer Kindly assign this task to me as a label of GSSOC'21
Thank you :)

**Comment by geekquad** [comment]
Hey @anubhav201241, it has already been assigned to someone else. Please check #8.

**Comment by anubhav201241** [comment]
Hi, Sir 

**Problem in the code:** 

The code is not fully optimized and have less feature in it. 

**What I want to add in it** 
So I want to add more feature and optimized python code in it
Feature I will be working upon is: 
1) Detects the Mid part in face.
2) Detects the eyes and face both Putting them in rectangle frame.
3) Which Detects the Eye and Face both part and also Detects the mid part of the face. 

**So please assign this updating  part to me so I can update this code and add some feature and value in it.**  
Thank You :))

**Comment by anubhav201241** [comment]
Hi, Sir I can add the following feature in it 

**I want to Add the code in Face_Detection file as it remains blank** 

Sir as You already assigned this code to someone else but I can assure you that I can work upon it since last 4-5 days and I'm confident that I can add some value, so sir can you please look into it and kindly assign this to me as it's remains blank for few days so I want contribute my code in it, which is ready to contribute if you assigned me this task ,I can  immediately  make a PR in  it 

**What I want to add in it**
So I want to add more feature and optimized python code in it
Feature I will be working upon is: 
1) Detects the Mid part in face.
2) Detects the eyes and face both Putting them in rectangle frame.
3) Which Detects the Eye and Face both part and also Detects the mid part of the face. 

**So please assign this updating  part to me so I can update this code and add some feature and value in it.**
Thank You :))
